# Generated by Django 3.2.4 on 2021-07-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anubis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='pais',
            field=models.CharField(default='Pais', max_length=15, verbose_name='Pais'),
            preserve_default=False,
        ),
    ]
